authors = ["suxiaoshao <https://github.com/suxiaoshao>"]
description = "Oxc support for Zed"
id = "oxc"
name = "Oxc"
repository = "https://github.com/oxc-project/zed-oxc"
schema_version = 1
version = "0.3.3"

[language_servers.oxc]
code_actions_kind = ["quickfix","source.fixAll.oxc"]
language = "JavaScript"
languages = [
    "JavaScript",
    "JSX",
    "TypeScript",
    "TSX",
    "Vue.js",
    "Astro",
    "Svelte",
]
name = "Oxc Language Server"

[language_servers.oxc.language_ids]
"Astro" = "astro"
"JSX" = "javascriptreact"
"JavaScript" = "javascript"
"Svelte" = "svelte"
"TSX" = "typescriptreact"
"TypeScript" = "typescript"
"Vue.js" = "vuejs"
